### ISSUE TITLE
[BUG] New version 0.12.1 CAN'T LOAD

### ISSUE THREAD

**Issue by sagitt** [ollo69/ha-smartthinq-sensors#261] opened 2022-01-09 01:33 UTC
**Describe the bug**
After upgrade, integration can't load.
Downgradig, all works fine.

Remove integration from list and re-add it is impossible, is not available in list.

**Environment details:**
 HASSOS on VM

**Comment by Xelinor** [comment] 2022-01-09 02:10
+1, I am experiencing this same issue on Home Assistant OS

**Comment by obs945** [comment] 2022-01-09 02:50
Same situation as sagitt but don't know how to downgrade. 

Environment details:
Home Assistant 2021.12.8 on Docker with Raspberry Pi 4

**Comment by Xelinor** [comment] 2022-01-09 03:16
> Same situation as sagitt but don't know how to downgrade.
> 
> Environment details: Home Assistant 2021.12.8 on Docker with Raspberry Pi 4

Go to HACS>Integrations> click on the 3 dots on the the SmartThinQ integration> go to redownload> select v0.12.0 from the drop-down and then click on download. Then it will update and then you need to restart like normal.

**Comment by adwolters** [comment] 2022-01-09 10:31
Same issue here. Downgrade did do the trick.

**Comment by TorbjornMohn** [comment] 2022-01-09 11:12
Same issue here. Downgrade to version 0.12.0 worked.

**Comment by tesliuk** [comment] 2022-01-09 11:16
Doesn't load even after downgrading.

**Comment by JohanTess** [comment] 2022-01-09 11:42
Yesterday migrated from Pi to NUC. LG refrigerator sensors were giving correct values. After the upgrade to V0.12 entities not working anymore. Loaded the backup again and working (V0.10.7). Will wait for the stable upgrade....wish I had known I just could redownload another version.

**Comment by modem** [comment] 2022-01-09 12:04
This is the 2nd addon with this issue in the last 2 days. I wonder if there's some wider issue...
I get this error in the logs after updating to v0.12.1:
`Setup failed for smartthinq_sensors: Integration not found.
11:56:18 – (ERROR) setup.py - message first occurred at 11:56:18 and shows up 2 times
`

**Comment by modem** [comment] 2022-01-09 12:11
Update: I re-downloaded the integration as suggested in 
https://github.com/zachowj/hass-node-red/issues/107
and it's now ok.

**Comment by ollo69** [comment] 2022-01-09 12:41
Could someone provide some more log about the error that cause the issue?

**Comment by sagitt** [comment] 2022-01-09 12:48
I solved. Downgrade, remove integration, restart, re-add i tegrarion so upgrade agin and works. Maybe a problem with token? Re-create token and upgrade may fix this issue.

**Comment by BebeMischa** [comment] 2022-01-09 13:30
redownload 0.12.0 temporalily fixed my integration.

**Comment by desosav** [comment] 2022-01-09 13:51
Same issue for me as well.

`Logger: homeassistant.setup
Source: setup.py:153
First occurred: 3:49:45 PM (1 occurrences)
Last logged: 3:49:45 PM

Setup failed for smartthinq_sensors: Integration not found.`

**Comment by ollo69** [comment] 2022-01-09 14:00
> Setup failed for smartthinq_sensors: Integration not found.`

Ok, so I'm quite sure that the issue is on HACS and not on this integration, I think that will be shortly released a fix for this. I wait for HACS fix before closing this

**Comment by tesliuk** [comment] 2022-01-09 14:02
> > Setup failed for smartthinq_sensors: Integration not found.`
> 
> Ok, so I'm quite sure that the issue is on HACS and not on this integration, I think that will be shortly released a fix for this. I wait for HACS fix before closing this

You are probably right. I have updated HACS to release issued just now (1.19.2) and was able to install anew this integration via HACS (did not risk it with the latest, used 0.12.0).

**Comment by ollo69** [comment] 2022-01-09 14:05
If someone with the problem should update HACS to last version and than update to 0.12.1 to check that everything is ok should be great.👍

**Comment by BebeMischa** [comment] 2022-01-09 14:10
downgrade LGE -> upgrade HACS -> upgrade LGE = works ;-)

**Comment by TorbjornMohn** [comment] 2022-01-09 14:34
I can confirm that Version 0.12.1 now works with HACS 1.19.2. Conclusion; do NOT upgrade to version 0.12.1 unless you already have updgraded HACS to 1.19.2.

**Comment by stappel** [comment] 2022-01-09 14:52
Mini is missing the integration in HASS itself.
I did a: upgrade LGE -> remove LGE -> upgrade HACS -> re-added LGE.
The integration does not give an alert anymore. But is cannot add it from HASS integrations. It is just not listed anymore.

**Comment by ollo69** [comment] 2022-01-09 14:56
> The integration does not give an alert anymore. But is cannot add it from HASS integrations. It is just not listed anymore.

Just try cleaning your browser cache

**Comment by stappel** [comment] 2022-01-09 15:08
> 

Damn, i had tried closing Chrome. You are right it needed to clean the cache from the browser. Solved

**Comment by ry8s** [comment] 2022-01-09 15:14
After updating HACS to the latest version, I was able to just 're-download' the LG integration and everything worked - no removing or setting anything up again.

Thanks!

**Comment by sagitt** [comment] 2022-01-09 16:21
same issue with other integration, i think is HACS bug

**Comment by ollo69** [comment] 2022-01-09 18:10
Closing this, was related to HACS issue.

**Closed by ollo69** 2022-01-09 18:10 UTC
