### ISSUE TITLE
Washtower Wont Connect

### ISSUE THREAD

**Issue by alozar64** [ollo69/ha-smartthinq-sensors#675] opened 2024-01-13 22:10 UTC
I have the following LG wash tower and it is not detecting with this integration. It does not find any devices. I have tried reloading it, and rebooting home assistant and it still wont detect it. 

https://www.lg.com/us/washers-dryers/lg-wkex300hba-washtower

![Screenshot 2024-01-13 140555](https://github.com/ollo69/ha-smartthinq-sensors/assets/156485938/87c48cb4-2101-4179-9e10-263536c25a7d)
![Screenshot 2024-01-13 140423](https://github.com/ollo69/ha-smartthinq-sensors/assets/156485938/5ad6accd-68d3-4eb0-9995-f0df18918874)

Any help would be appreciated.

**Comment by southwestflavorz** [comment] 2024-01-28 21:38
I'm experiencing the same issue with the same model. Anything we can do to fix this?

**Comment by ollo69** [comment] 2024-01-28 23:15
This is duplicate of #649, so I close this.
Working to implement this new device.

**Closed by ollo69** 2024-01-28 23:15 UTC
