### ISSUE TITLE
Not working on 2024.4.0b0

### ISSUE THREAD

**Issue by TheFes** [ollo69/ha-smartthinq-sensors#725] opened 2024-03-27 18:45 UTC
**Describe the bug**
Integration is not working and this message appears in the log
```
Logger: homeassistant.setup
Source: setup.py:273
First occurred: 19:40:01 (1 occurrences)
Last logged: 19:40:01

Setup failed for custom integration 'smartthinq_sensors': Requirements for smartthinq_sensors not found: ['pycountry<23.0.0,>=22.1.10'].
```

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): HAOS
 - Home Assistant version installed: 2024.4.0b0
 - Component version installed: v0.38.7
 - Last know working version: HA 2024.3
 - LG device type and model with issue: NA
 - LG devices connected (list): NA

**Output of HA logs**
Paste the relavant output of the HA log here.

```
Logger: homeassistant.setup
Source: setup.py:273
First occurred: 19:40:01 (1 occurrences)
Last logged: 19:40:01

Setup failed for custom integration 'smartthinq_sensors': Requirements for smartthinq_sensors not found: ['pycountry<23.0.0,>=22.1.10'].
```

**Additional context**

**Comment by ollo69** [comment] 2024-03-27 20:57
Thanks for information, I suppose that some integration install other version. Do you have `web radio` installed? 
Anyway I will change requirement to be less restrictive

**Comment by TheFes** [comment] 2024-03-27 21:34
Do you mean [Radio Browser](<https://rc.home-assistant.io/integrations/radio_browser>)?
I have that one installed.

I asked about pycountry in the beta channel on the HA Discord, the response was:
> It’s pinned to the newer than 23 because there is a mistake in the older versions that brings in the whole setuptools stack

**Comment by nickrout** [comment] 2024-03-27 21:48
Just to say "me too" - precisely the same issue. (Sorry if me too is frowned on)

**Comment by luisiam** [comment] 2024-03-28 02:17
> Thanks for information, I suppose that some integration install other version. Do you have `web radio` installed? Anyway I will change requirement to be less restrictive

I don't have that installed but I also have this issue.

**Comment by pcartwright81** [comment] 2024-03-28 03:45
This seems the same as issue 693 so I posed it last week there.  I edited manifest.json at the location \\homeassistant.local\config\homeassistant\custom_components\smartthinq_sensors to say pycountry>23.0.0 and it seems to be working now.

**Comment by nickrout** [comment] 2024-03-28 05:00
@pcartwright81 suggestion seems to work for me, but I don't feel confident enough about python modules to create a PR.

**Comment by nickrout** [comment] 2024-03-28 05:17
Home assistant seems to have constrained pycountry to >23.12.11 two weeks ago.

https://github.com/home-assistant/core/commit/f3984a9d3ee94b92fd5a1a8902532d436ca52353

This custom integration constrains pycountry to pycountry<23.0.0,>=22.1.10

You can't be >23.12.11 and <23.0.0. I suspect that is the problem.

**Comment by cloudbr34k84** [comment] 2024-03-28 07:05
Just noticed this as well when I upgraded to 2024.4.0b0

**Comment by sunny-ww** [comment] 2024-03-28 09:34
> This seems the same as issue 693 so I posed it last week there. I edited manifest.json at the location \\homeassistant.local\config\homeassistant\custom_components\smartthinq_sensors to say pycountry>23.0.0 and it seems to be working now.

the solution also worked perfectly for me

**Comment by pjannink** [comment] 2024-03-28 09:41
Noticed too after installing 2024.4.0b0 on my testconfig.. Not using Webradio. I edited manifest.json as advised above but changing the line to   "requirements": ["pycountry<23.0.0,>=22.1.10", "xmltodict>=0.13.0", "charset_normalizer>=3.2.0"],
 did not solve the issue. Please advise!

**Comment by smarthomeaf** [comment] 2024-03-28 11:41
Same issue on a clean 2024.4B0.  Meaning nothing else installed other than smarthinq.  Still works great on my 2024.3

**Comment by def1149** [comment] 2024-03-28 14:00
Confirmed:
Issue fixed with line "requirements": ["**pycountry>23.0.0**", "xmltodict>=0.13.0", "charset_normalizer>=3.2.0"],

**Comment by cloudbr34k84** [comment] 2024-03-28 14:02
updated and fixed, and appears to be working again.

**Comment by nelsonpita** [comment] 2024-03-28 15:30
> This seems the same as issue 693 so I posed it last week there. I edited manifest.json at the location \\homeassistant.local\config\homeassistant\custom_components\smartthinq_sensors to say pycountry>23.0.0 and it seems to be working now.

**Comment by nelsonpita** [comment] 2024-03-28 15:31
Change to   "requirements": ["pycountry>23.0.0,>=22.1.10", "xmltodict>=0.13.0", "charset_normalizer>=3.2.0"],
, restart HA and now it is working.

**Comment by kimwowboom** [comment] 2024-03-30 20:05
The following integrations and platforms could not be set up:

[smartthinq_sensors](https://github.com/ollo69/ha-smartthinq-sensors)

Config-flow kon niet geladen worden: 500 Internal Server Error Server got itself in trouble

**Comment by gershte** [comment] 2024-03-30 20:44
Still not loading 

Logger: homeassistant.setup
Source: setup.py:273
First occurred: 4:35:00 PM (1 occurrences)
Last logged: 4:35:00 PM

Setup failed for custom integration 'smartthinq_sensors': Requirements for smartthinq_sensors not found: ['pycountry<23.0.0,>=22.1.10'].

**Comment by ollo69** [comment] 2024-03-30 23:39
@All,

issue should be fixed with last release [v0.39.0](https://github.com/ollo69/ha-smartthinq-sensors/releases/tag/v0.39.0), please report here if you still have problem.

**Comment by kimwowboom** [comment] 2024-03-30 23:43
> @ALL,
> 
> issue should be fixed with last release [v0.39.0](https://github.com/ollo69/ha-smartthinq-sensors/releases/tag/v0.39.0), please report here if you still have problem.

Update is not mentioned/pushed as update in HA/HACS store? It needs to be updated manually?

**Comment by ollo69** [comment] 2024-03-30 23:51
If you don't wait to wait the HACS auto refresh  you need to force repository update selecting HACS integration

![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/60491700/7c46f8c9-7947-4c7e-9fe9-58ddb83dbfe8)

**Comment by kimwowboom** [comment] 2024-03-30 23:57
Cool. That worked! Love you.

**Comment by gershte** [comment] 2024-03-31 02:25
> @ALL,
> 
> issue should be fixed with last release [v0.39.0](https://github.com/ollo69/ha-smartthinq-sensors/releases/tag/v0.39.0), please report here if you still have problem.

Confirmed. Problem solved. Thank you!

**Comment by NukeThemTillTheyGlow** [comment] 2024-04-04 12:29
Update applied and works, thanks!

**Comment by kfiducia** [comment] 2024-04-05 00:46
thanks for the quick patch on this!

**Comment by ollo69** [comment] 2024-05-04 09:12
Close this because fixed with last release

**Closed by ollo69** 2024-05-04 09:12 UTC
