### ISSUE TITLE
Error in Home Assistant Log

### ISSUE THREAD

**Issue by musicscoree96** [ollo69/ha-smartthinq-sensors#707] opened 2024-02-22 15:45 UTC
**Describe the bug**
I see this error in the log :

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Klimaat ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 16:31:50 (9 occurrences)
Last logged: 16:31:50

Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues
Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues
Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) implements HVACMode(s): off, heat, dry, cool, fan_only, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

**Expected behavior**
Everything seems to work correctly

**Screenshots**

**Environment details:**
 - Environment :
 Core 2024.2.2
Supervisor 2024.02.0
Operating System 11.5
Frontend  20240207.1
 - Component version installed: 0.38.3
 - Last know working version: Still working
 - LG device type and model with issue: Airco Units -> RAC_056905_WW-RAC (AC)
 - LG devices connected (list): 3 units

**Output of HA logs**
Paste the relavant output of the HA log here.

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Klimaat ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 16:31:50 (9 occurrences)
Last logged: 16:31:50

Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues
Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues
Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) implements HVACMode(s): off, heat, dry, cool, fan_only, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

**Additional context**

**Comment by ollo69** [comment] 2024-02-22 16:24
Close as duplicate of #692.

**Closed by ollo69** 2024-02-22 16:24 UTC
