### ISSUE TITLE
power off does not work

### ISSUE THREAD

**Issue by felisida** [ollo69/ha-smartthinq-sensors#581] opened 2023-08-16 16:26 UTC
**Describe the bug**
integration recognizes the status of the dryer, but when I try to turn it off from HA it returns the error and does not work

**Environment details:**
Home Assistant 2023.8.2
Supervisor 2023.08.1
Operating System 10.4
Frontend 20230802.0 - latest
 - Environment (HASSIO, Raspbian, etc): Proxomx
 - Home Assistant version installed: HA supervised
 - Component version installed:
 - Last know working versionit: iy has never worked
 - LG device type and model with issue: drier rc90v9
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.smartthinq_sensors.wideq.device
Source: custom_components/smartthinq_sensors/wideq/device.py:688 
Integration: SmartThinQ LGE Sensors (documentation, issues) 
First occurred: 18:09:38 (2 occurrences) 
Last logged: 18:22:59

Connection to ThinQ failed. Timeout error - Device: Asciugatrice
Connection to ThinQ failed. Network connection error - Device: Asciugatrice

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/smartthinq_sensors/wideq/core_async.py:359 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 18:14:59 (1 occurrences) 
Last logged: 18:14:59

[140439509669824] 0111 - {'data': None}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/switch.py", line 271, in async_turn_on
    await self.entity_description.turn_on_fn(self._wrap_device)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 252, in wake_up
    await self.set_with_retry(keys[0], keys[1], value=keys[2], num_retry=2)
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 292, in set_with_retry
    await self.set(
  File "/config/custom_components/smartthinq_sensors/wideq/devices/washerDryer.py", line 267, in set
    await super().set(
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 517, in set
    await self._set_control(full_key, ctrl_path=ctrl_path)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 489, in _set_control
    await self._client.session.device_v2_controls(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1192, in device_v2_controls
    res = await self.post2(cmd_path, payload)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1029, in post2
    return await self._auth.gateway.core.lgedm2_post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 346, in lgedm2_post
    return self._manage_lge_result(out, is_api_v2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 359, in _manage_lge_result
    raise exc.APIError(message, code)
custom_components.smartthinq_sensors.wideq.core_exceptions.APIError: 0111 - {'data': None}

**Additional context**

**Comment by C09038** [comment] 2023-08-18 19:02
I have the same issue

**Comment by w-marco** [comment] 2023-08-20 10:37
Might be this issue?
https://github.com/ollo69/ha-smartthinq-sensors/issues/489

**Comment by ollo69** [comment] 2023-08-20 14:24
Closed as duplicate of #489

**Closed by ollo69** 2023-08-20 14:24 UTC
