### ISSUE TITLE
Problem in the integration

### ISSUE THREAD

**Issue by JPOliveGit** [ollo69/ha-smartthinq-sensors#149] opened 2021-04-26 17:19 UTC
**Describe the bug**
I don't know why but starting today the integration broke, everything LG stopped working in the home assistant, I tried everything, but after I removed the integration I reinstalled again, it shows installed the version 0.6.8 and it never showed up again in the integrations in home assistant, I tried to manually via config yaml to insert the token and country again but it's not working

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Raspberry PI
 - Home Assistant version installed: 2021.4.6
 - Component version installed: 0.6.8

**Output of HA logs**
Logger: homeassistant.setup
Source: custom_components/smartthinq/__init__.py:69 
First occurred: 18:14:00 (1 occurrences) 
Last logged: 18:14:00

Error during setup of component smartthinq
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 242, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq/__init__.py", line 69, in setup
    client = wideq.Client.from_token(refresh_token, region, language)
  File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 209, in from_token
    client._auth = core.Auth(client.gateway, None, refresh_token)
  File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 103, in gateway
    self._gateway = core.Gateway.discover(
  File "/usr/local/lib/python3.8/site-packages/wideq/core.py", line 318, in discover
    gw = lgedm_post(GATEWAY_URL,
  File "/usr/local/lib/python3.8/site-packages/wideq/core.py", line 202, in lgedm_post
    res = session.post(url, json={DATA_ROOT: data}, headers=headers)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by ollo69** [comment] 2021-04-26 18:18
The log error is referring to before or after component re-istallation?

**Comment by JPOliveGit** [comment] 2021-04-26 21:45
After

**Comment by ollo69** [comment] 2021-04-26 22:00
Sorry but it is not clear to me what you did. Seems that you are still using old API version that is not supported and used by the integration from a long time. As is not supported anymore configuration using `yaml`.
It is possible that LG dismiss some old server and for this reason you are receiving the error `'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')`
You probably have an old configuration in the registry that should be removed from the integration page, than reconfigure the integration using the config flow. Also remove any configuration present in `configuration.yaml`.

**Comment by prnewman** [comment] 2021-04-29 19:18
The latest release broke my integration as well. I have an LG LRFXC2406S refrigerator, and its three sensors are now "unavailable." 
![image](https://user-images.githubusercontent.com/857199/116605522-85357f00-a8fd-11eb-9b66-079336c37bf4.png)

**Comment by ollo69** [comment] 2021-04-29 20:20
Remove any configuration from yaml and reconfigure integration from integration page.

**Comment by prnewman** [comment] 2021-04-30 16:03
@ollo69 Thanks for your help. I deleted and re-added the integration and all the sensors are back online.

**Comment by usedjeans818** [comment] 2021-04-30 23:59
I had to both delete the Integration and uninstall the Repository then add everything back in before the Integration would accept the URL.  However, my sensors are working again as well.

**Comment by Gahrlaag** [comment] 2021-05-04 21:19
I've tried everything from removing the repository to removing the integration. Still no success after updating. All of the sensors are gone and going through the registration process does nothing. I can finalize the integration part, but no sensors show up. Region SE and language EN

**Comment by ollo69** [comment] 2021-05-04 21:56
Check your LG phone application that device are properly shown. Provide log information to check what is happening during integration setup.

**Comment by Gahrlaag** [comment] 2021-05-04 22:20
> Check your LG phone application that device are properly shown. Provide log information to check what is happening during integration setup.

The device shows up when looking at the phone app. When providing the response url, it completes the setup but no sensors show up basically

**Comment by Gahrlaag** [comment] 2021-05-04 22:21
Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_v2.py:812
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 4 May 2021, 23:19:54 (48 occurrences)
Last logged: 0:20:36

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb7391cbb20>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='objectcontent.lgthinq.com', port=443): Max retries exceeded with url: /ced540ef-858e-4dd3-aec4-0628f0fa4a8f?hdnts=exp=1674702047~hmac=575577646661f765e2b346e5a8ee2872b5320d5e0ef09061deb970a9040d5ff2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb7391cbb20>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 205, in async_setup_entry
    lge_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 581, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 337, in init_device
    result = await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 775, in init_device_info
    self._model_data = self._client.model_url_info(
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 841, in model_url_info
    self._model_url_info[url] = self._load_json_info(url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_v2.py", line 812, in _load_json_info
    resp = requests.get(info_url, timeout=DEFAULT_TIMEOUT).text
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='objectcontent.lgthinq.com', port=443): Max retries exceeded with url: /ced540ef-858e-4dd3-aec4-0628f0fa4a8f?hdnts=exp=1674702047~hmac=575577646661f765e2b346e5a8ee2872b5320d5e0ef09061deb970a9040d5ff2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb7391cbb20>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by Gahrlaag** [comment] 2021-05-05 07:13
Ok...so I went to bed, woke up and everything was there in the morning. No idea what happened

**Comment by ollo69** [comment] 2021-05-05 09:56
It is because I implemented a sophisticated AI algorithm able to autofix bug inside integration  😊🤣😁.
Or just because the LG server was not reachable or you was having an issue with internet connection

**Comment by ollo69** [comment] 2021-05-10 20:04
Can we close this issue?

**Comment by ollo69** [comment] 2021-06-12 10:34
Close because no feed-back from more than one months

**Closed by ollo69** 2021-06-12 10:34 UTC
