### ISSUE TITLE
Jet mode switch is unavailable when AC is OFF

### ISSUE THREAD

**Issue by snp88** [ollo69/ha-smartthinq-sensors#381] opened 2022-09-01 13:47 UTC
**Describe the bug**

When AC is in OFF state entity related to Jet Mode switch became unavailable 

**Expected behavior**

I think this switch should be in OFF state when the AC is OFF and when i Turn ON this switch it should also turn on whole AC

**Screenshots**
![image](https://user-images.githubusercontent.com/46537540/187929482-572c8974-a8de-4be5-b599-de7e690a6ae4.png)

**Environment details:**
 - Environment (HASSIO, Raspbian, etc): Virtual Machine
 - Home Assistant version installed: Latest
 - Component version installed: 0.24.2
 - Last know working version: not sure notice today
 - LG device type and model with issue: LG Standard 2
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by ollo69** [comment] 2022-09-01 14:35
This is not a bug!
Because the Jet mode depend on the current mode (cold, dry, or warm), the device must be turned-on in one of this 3 modes to be able to use it and determine the action based on the selected mode.
If the device is off or other mode, jet mode will not be available.

**Comment by snp88** [comment] 2022-09-02 09:02
I just try to say that unavailable status in HA is more related that something is wrong with the entity.
I think unavailable in this case is misleading

**Comment by ollo69** [comment] 2022-09-02 09:04
I don't think exist others way to disable a switch in HA.

**Comment by Rahulsharma0810** [comment] 2022-10-01 06:46
I used https://github.com/nVuln/homebridge-lg-thinq in homebridge, this plugin also exposes a jet mode switch however, if you enable the button it will set Ac to High cool, which is the default for most of the AC.

Any option to use the same option, High Cool on. jet mode toggle?, Seeing the "NO response" switch in Homekit is irritating.

**Comment by snp88** [comment] 2022-11-17 08:48
> I used https://github.com/nVuln/homebridge-lg-thinq in homebridge, this plugin also exposes a jet mode switch however, if you enable the button it will set Ac to High cool, which is the default for most of the AC.
> 
> Any option to use the same option, High Cool on. jet mode toggle?, Seeing the "NO response" switch in Homekit is irritating.

I would expect the same behavior here

**Comment by ollo69** [comment] 2022-12-21 13:26
Ok, I'll try to change this in next release just turning on AC if it is off. I will not care about HVAC Mode, I just will use last selected.

**Comment by ollo69** [comment] 2022-12-21 20:40
Before doing something here, can someone explain how the LG application or AC remote control works? Does it allow to set JET mode when AC is off? Because JET mode have some constrain related to HVAC mode and model supported features and it is not so simple manage all possible conditions. I understand that exist a plugin that do not follow the rules and just turn AC on, but maybe this works only with some models and with other just fails. And it is quite simple create an automation in HA that:
1) turn on AC
2) set desired HVAC mod2
3) turn JET mode on

I wait for feed-back.

**Comment by Rahulsharma0810** [comment] 2022-12-21 21:10
I have a PS-Q13SWZ model that I have to turn on via remote, and then only the HC button works.

If you talk about a V2 API, turning it on via HC will support all the AC. the solution should be around not seeing a no response on the jet mode accessory maybe when jet mode is pressed, internally turn on ac and set it to jet mode.

**Comment by ollo69** [comment] 2022-12-21 23:21
> the jet mode accessory maybe when jet mode is pressed, internally turn on ac and set it to jet mode.

The point is that this solution could not work for all models. Not all model support Jet in both Hot and Cool mode, and I should choose the right action based on multiple conditions (previous HVAC mode, supported features, bla bla bla...). It is more complex than you can suppose and for this reason is disabled when AC is off.

**Comment by gabi1324** [comment] 2023-01-09 21:05
Hello! If I press the Jet mode button while the unit is off, the AC doesn't react or turn on. I think the switch's current behavior is okay because it mirrors the behavior of the remote.

**Comment by ollo69** [comment] 2023-01-15 23:45
Thanks @gabi1324,

this make sense, basically because when the AC device is off doesn't know if you want if you need jet mode for cold of warm mode. 
I close this, behavior is correct as is as reflecting AC working mode.

**Closed by ollo69** 2023-01-15 23:45 UTC
