### ISSUE TITLE
Authorization does not go through

### ISSUE THREAD

**Issue by Reydan46** [ollo69/ha-smartthinq-sensors#351] opened 2022-07-07 10:50 UTC
**It is impossible to enter**
After updating Home Assistant 2022.6.7> 2022.7.0 demanded to authorize in "SmartThinQ LGE Sensors".
After removing "Smartthinq Lge Sensors" and re -adding integration, authorization does not go through any way (standard, through form and "url redirect authentication method")

**Screenshots**
![image](https://user-images.githubusercontent.com/4998320/177756442-e92c1cb5-ef2d-40c0-87ad-ebe5ed86c31a.png)
![image](https://user-images.githubusercontent.com/4998320/177755489-ad2a353f-d2ef-43ad-a447-2ac3dce5e109.png)

**Details of the environment:**
  - Environment: Home Assistant OS
  - The version of the home assistant was installed: 2022.7.0
  - The component version has been installed: 0.23.3
  - The last to know the working version: 0.23.3
  
**Conclusion of HA magazines**
```
2022-07-07 13:26:21 ERROR (MainThread) [custom_components.smartthinq_sensors.config_flow] Error connecting to ThinQ
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 708, in from_user_login
    token_info = await gateway.core.auth_user_login(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 383, in auth_user_login
    async with self._session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 990, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host ru.emp.lgsmartplatform.com:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/config_flow.py", line 184, in _check_connection
    client = await lge_auth.create_client_from_login(
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 105, in create_client_from_login
    return await ClientAsync.from_login(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1198, in from_login
    auth = await Auth.from_user_login(gateway, username, password)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 715, in from_user_login
    raise exc.AuthenticationError() from ex
custom_components.smartthinq_sensors.wideq.core_exceptions.AuthenticationError: Authentication Error
```

**Additional context**
Through the "LG ThinQ" **application**, authorization is **successful**.
With standard authorization (through the form), an error "Invalid SmartThinQ credentials. Try again, and make sure you can access the ThinQ app on your phone." (see Screenshots) and the log (see "Conclusion of HA magazines").
When authorizing "URL redirect authentication method" and the transition to the generated link in the browser there is an error (see Screenshots):
URL - https://emp-oauth.lgecloud.com/emp/oauth2/token/empsession
RESPONSE - {"status":2,"lgoauth_error_code":"LG.OAUTH.EC.2105","message":"Signature doesn't match request."}

**Comment by ollo69** [comment] 2022-07-07 11:15
This issue is related to Python 3.10 and new security restrictions. I need to install python on my env to solve this.

**Comment by ollo69** [comment] 2022-07-09 15:22
I installed Python 3.10 in my enviroment, but I'm not able to reproduce the issue. I think that problem is related to LG servers in your region that still use RSA key exchange, not allowed by Python 3.10. I'm thinking about an option to use in initial configuration to allow lower security to solve this problem, but I will not be able in any case to test this solution.

**Comment by divanikus** [comment] 2022-07-10 12:28
Having the same problem, though the error is different. And I don't think it related to old encryption. Tried curling it

```
*   Trying 158.255.4.60:80...
* Connected to ru.m.lgaccount.com (158.255.4.60) port 80 (#0)
> GET / HTTP/1.1
> Host: ru.m.lgaccount.com
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Date: Sun, 10 Jul 2022 12:24:11 GMT
< Server: Apache
< Location: https://ru.m.lgaccount.com/
< Content-Length: 211
< Content-Type: text/html; charset=iso-8859-1
<
* Ignoring the response-body
* Connection #0 to host ru.m.lgaccount.com left intact
* Clear auth, redirects to port from 80 to 443
* Issue another request to this URL: 'https://ru.m.lgaccount.com/'
*   Trying 158.255.4.60:443...
* Connected to ru.m.lgaccount.com (158.255.4.60) port 443 (#1)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=ru.m.lgaccount.com
*  start date: Feb 21 00:00:00 2022 GMT
*  expire date: Mar 24 23:59:59 2023 GMT
*  subjectAltName: host "ru.m.lgaccount.com" matched cert's "ru.m.lgaccount.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=Thawte RSA CA 2018
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: ru.m.lgaccount.com
> User-Agent: curl/7.83.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 200
< Date: Sun, 10 Jul 2022 12:24:11 GMT
< Server: Apache
< Set-Cookie: JSESSIONID=70D1887C2754D6DE8F26B535424699B2.sdpempf_22680_10; Path=/; Secure; HttpOnly
< X-dynaTrace-JS-Agent: true
< Set-Cookie: dtCookie=F990472D3A0BDF2C3B33E2EA5F6D73A5|X2RlZmF1bHR8MQ; Path=/; Domain=.lgaccount.com
< Content-Length: 83
< Content-Type: text/html;charset=UTF-8
<
```

Mine error looks like this though
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 708, in from_user_login
    token_info = await gateway.core.auth_user_login(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 365, in auth_user_login
    async with self._session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host ru.m.lgaccount.com:443 ssl:default [Try again]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/config_flow.py", line 184, in _check_connection
    client = await lge_auth.create_client_from_login(
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 105, in create_client_from_login
    return await ClientAsync.from_login(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1198, in from_login
    auth = await Auth.from_user_login(gateway, username, password)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 715, in from_user_login
    raise exc.AuthenticationError() from ex
custom_components.smartthinq_sensors.wideq.core_exceptions.AuthenticationError: Authentication Error
```

**Comment by divanikus** [comment] 2022-07-10 12:34
Why isn't redirect method working though? I'm able to login if I remove client_id=LGAOXXXXX part of the url. Otherwise it's "Signature doesn't match request"

**Comment by divanikus** [comment] 2022-07-10 12:44
I'v also tryed the generic method used by `wideq`, i mean `example.py` thing. I was able to authorize with it and got the list my devices

**Comment by GenoMXXX** [comment] 2022-07-11 17:38
Same problem

**Comment by ollo69** [comment] 2022-07-11 21:15
I understand that there are some problem on some LG server (probably `ru`) but I don't have any issue with my account. If someone with issue could share his LG account, setting a temporary password, I can perform next w.e. some test on my environment to try to fix the issue. If I cannot reproduce the issue, I will not be able to try to fix this. 
If somebody is interested to share account for tests, I will provide my e-mail to share credential.

**Comment by GenoMXXX** [comment] 2022-07-12 06:47
Good afternoon! Thank you, this problem has been resolved. For some reason, it is not possible to authenticate from the same local network where HA is located using a reverse proxy. Authorization succeeded by fulfilling a link and authorization request from the outside world.

**Comment by divanikus** [comment] 2022-07-12 08:15
@GenoMXXX Could you explain exactly what you did?

@ollo69 I can share you my account

**Comment by GenoMXXX** [comment] 2022-07-12 08:35
> @GenoMXXX Could you explain exactly what you did?

All I did was go to HA not from the local network, but remotely, via the Internet. I requested the formation of a link and, upon authorization in the LG account, I received the correct link-response without errors. The integration succeeded, but now an error occurs.
ThinQ platform not ready

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_async.py:228
Integration: SmartThinQ LGE Sensors ([documentation](https://github.com/ollo69/ha-smartthinq-sensors), [issues](https://github.com/ollo69/ha-smartthinq-sensors/issues))
First occurred: 11 июля 2022 г., 21:53:15 (492 occurrences)
Last logged: 08:58:22

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 213, in async_setup_entry
    lge_devices, unsupported_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 435, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 323, in init_device
    if not await self._device.init_device_info():
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 979, in init_device_info
    self._model_data = await self._client.model_url_info(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1301, in model_url_info
    self._model_url_info[url] = await self._load_json_info(url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1259, in _load_json_info
    content = await self._auth.gateway.core.http_get_bytes(info_url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 228, in http_get_bytes
    async with self._session.get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 990, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host ruic.lgthinq.com:46030 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)]

**Comment by divanikus** [comment] 2022-07-12 09:00
Didn't worked for me. I've tried to access my HA server from external URL, no luck, same problem. Also tried to use VPN to access LG servers - didn't worked either. Though I started to get SSLV3_ALERT_HANDSHAKE_FAILURE error, quite interesting,

**Comment by ollo69** [comment] 2022-07-12 16:23
@divanikus, 

send me your credential at aolivero@gmail.com. Please note that I will not be able to do any test until this w.e.

**Comment by ArmoredCavalry** [comment] 2022-07-14 14:53
Just to add some additional info here, this error starting occurring for me when I was still on Home Assistant 6.7, so it seems unrelated to the July HA update? After I updated to 7.4, I'm still getting the same authorization error.

**Comment by ArmoredCavalry** [comment] 2022-07-14 19:44
@dtmaiale thanks for that info! My issue turned out to be just the Terms of Service needed accepting in the LG app (oops!), and then it worked fine after a restart of HA. Didn't need to change anything with Python.

**Comment by tayanov** [comment] 2022-07-16 08:06
> I understand that there are some problem on some LG server (probably `ru`) but I don't have any issue with my account. If someone with issue could share his LG account, setting a temporary password, I can perform next w.e. some test on my environment to try to fix the issue. If I cannot reproduce the issue, I will not be able to try to fix this. If somebody is interested to share account for tests, I will provide my e-mail to share credential.

i can share RU account. my telegram @tayanov

**Comment by GenoMXXX** [comment] 2022-07-16 09:13
I passed the authorization, but... The integration works correctly when only a refrigerator is connected to the device of the LG account. After I add conditioner, the integration stops working with "Platform not ready" error

**Comment by ollo69** [comment] 2022-07-17 15:22
@divanikus,

I tried to make some test with your credential, but I think that your user is locked (I see a message that say something like wrong password was inserted too much time)

@tayanov,

if you want share your credential, send e-mail to aolivero@gmail.com

@GenoMXXX,

please open a new issue and provide logs and diagnostics, from your description seems different issue.

**Comment by divanikus** [comment] 2022-07-18 00:37
@ollo69 I'm not sure what it means, because I can successfully login into mobile app and use it. I'm also getting notifications etc

**Comment by ollo69** [comment] 2022-07-18 20:10
> I'm not sure what it means, because I can successfully login into mobile app and use it. I'm also getting notifications etc

Could you try to logout from LG App and login again and see what happen?

**Comment by Reydan46** [comment] 2022-07-19 04:51
> Could you try to logout from LG App and login again and see what happen?

The exit from the account in the LG ThinQ application and repeated authorization are successful, without additional requests.
With a decrease in Home Assistant to the version 2022.6.7, the authorization in the expansion of "Smartthinq Lge Sensors" is successful.
After a successful entrance and updating the version of Home Assistant to the actual - authorization disappears.

**Comment by ollo69** [comment] 2022-07-19 06:33
What do you mean with "authorization disappears"?

**Comment by tayanov** [comment] 2022-07-19 08:04
hi. i have 2 lg devices. Wash and fridge. If i add to APP only washer machine, all sensor work perfectly in HA 2022.7.5 (last version)
But if i try add fridge to APP. i see error at HA. [ollo69](https://github.com/ollo69) i send for your two email. second mail have my account for test. But now fridge is femoved from APP. (add it later)

**Comment by Reydan46** [comment] 2022-07-20 07:41
> "authorization disappears"

In the Home Assistant interface, repeated authorization is requested.

In version 6.7 everything connects and works.
There is no way to log in to the expansion in the old version (6.7) and upgrade to the new (7.x) while maintaining authorization in expansion.

It follows that this problem is precisely in expansion, and not in LG servers.

**Comment by suarezcp87** [comment] 2022-07-21 16:03
Hello, have the same problem on 2022.6.5 work, after update 2022.7.6 dont work


Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_async.py:239
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 18:46:07 (19 occurrences)
Last logged: 19:01:33

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 235, in async_setup_entry
    lge_devices, unsupported_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 458, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 346, in init_device
    if not await self._device.init_device_info():
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line 979, in init_device_info
    self._model_data = await self._client.model_url_info(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1321, in model_url_info
    self._model_url_info[url] = await self._load_json_info(url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1279, in _load_json_info
    content = await self._auth.gateway.core.http_get_bytes(info_url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 239, in http_get_bytes
    async with self._get_session().get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 990, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host ruic.lgthinq.com:46030 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)]

**Comment by ollo69** [comment] 2022-07-21 20:38
@tayanov,

I was able to authenticate with your account using Python 3.9 and everything woks fine (I see both washer and refrigerator).
I will make some tests with python 3.10 this w.e. to try to found a fix for this issue, in the meantime please do not change your account configuration.

Thanks,👍

**Comment by ollo69** [comment] 2022-07-22 19:26
Please install last release that should fix this issue.

**Comment by Reydan46** [comment] 2022-07-22 19:46
Checked, everything works. Many thanks!

**Comment by Enzokot** [comment] 2022-07-22 19:56
Everything works for me, thanks!

**Comment by suarezcp87** [comment] 2022-07-22 20:12
Many thanks!

**Comment by tayanov** [comment] 2022-07-23 16:16
switch.kholodilnik_express_freeze changed to switch.kholodilnik_ice_plus, why?

**Comment by divanikus** [comment] 2022-07-23 17:12
@ollo69 I can confirm it works now. And yes, my account was kind of blocked and asked to "authorize by email" kind of thing. I have reset the password and now it works both in HA and mobile app.

**Comment by gopheridze** [comment] 2022-07-23 18:04
I also confirm that authorization works now. Thanks for the fix.

**Comment by ollo69** [comment] 2022-07-23 18:42
> switch.kholodilnik_express_freeze changed to switch.kholodilnik_ice_plus, why?

@tayanov,

If you have a problem please open a new issue and attach diagnostic

**Comment by ollo69** [comment] 2022-07-23 18:43
I close this issue, seems it is solved for everybody.

**Closed by ollo69** 2022-07-23 18:43 UTC
