### ISSUE TITLE
LG washer water temp not reporting correct unit of measurements

### ISSUE THREAD

**Issue by mspinolo** [ollo69/ha-smartthinq-sensors#458] opened 2022-12-31 14:03 UTC
**Describe the bug**
It looks like unit of measurements it is not correctly set: although output for the sensor is like "30°C" it is not displayed as line graph but as bar state

![image](https://user-images.githubusercontent.com/43354538/210139303-e30f8728-c385-4d77-8cf1-c7763845f397.png)

**Environment details:**
 - HASSIO
 - Home Assistant version installed: 2022.12.8
 - Component version installed: 0.28
 - Last know working version: N/A
 - LG device type and model with issue: see below pic
 - LG devices connected (list): only the one above

![image](https://user-images.githubusercontent.com/43354538/210139330-680bc266-2d3b-4a16-ae72-a727f92e1e9c.png)

**Comment by ollo69** [comment] 2022-12-31 17:51
This is not a bug. 
Water temperature for washer just represent the select temperature for the programs and not real water temperature, so having a graph does not make sense because will be always a straight line.

**Comment by ollo69** [comment] 2023-01-15 23:49
I close this, for reason described above and because I did not receive any comments. Nothing to fix here.

**Closed by ollo69** 2023-01-15 23:49 UTC
