### ISSUE TITLE
[BUG] Room temperature is not being displayed correctly

### ISSUE THREAD

**Issue by hros** [ollo69/ha-smartthinq-sensors#166] opened 2021-05-28 10:04 UTC
room temperature is not being displayed correctly
if I remember correctly it was working in previous versions of the plugin, but in the current version (0.8.2) it is not being updated

additionally, there is a UI issue which is probably not related directly to this plugin:
I have changed the settings of the a/c so that I can modify the target temperature by 0.5 °C
I have set the target temperature to 24.5 °C, however the UI shows 25 °C (note, current temperature is not 28 °C):
![image](https://user-images.githubusercontent.com/2613469/119967310-e318bd80-bfb4-11eb-9f28-ee4fd4d43681.png)
When I look at the detailed information (pressing the three dots), I see the correct target temperature:
![image](https://user-images.githubusercontent.com/2613469/119967514-178c7980-bfb5-11eb-95ea-422c30a90133.png)

**Comment by ollo69** [comment] 2021-05-28 11:46
Issue about room temperature was already discussed in other thread. When do you think it was working properly? Are you able to confirm this, may be installing previous version?

About target temperature I will check, but seems a problem related to UI and not integration.

**Comment by hros** [comment] 2021-05-28 12:10
How would like me to confirm this?
Is there a specific previous version I should install (I'll have to check how to install older versions using HACS)

regarding the target temperature, if it is UI related - what is the relevant development repo? I would like to open an issue (or perhaps prepare a PR)

**Comment by ollo69** [comment] 2021-05-28 12:43
> How would like me to confirm this?
> Is there a specific previous version I should install (I'll have to check how to install older versions using HACS)

In HACS you can select specific version to install. AC support is available just from version 7.0, but the only version where I introduced a change to try to fix issue is 0.8.1. Should be very strange that other version update room temperature properly.



> regarding the target temperature, if it is UI related - what is the relevant development repo? I would like to open an issue (or perhaps prepare a PR)

This is a standard  HA UI. Refer to HA repository.

**Comment by DivanX10** [comment] 2021-05-28 12:55
There was a problem. The air conditioner does not turn on if I press the on button, but you can turn it off. If I click on the cooling or ventilation icon, the air conditioner turns on.
![image](https://user-images.githubusercontent.com/64090632/119986636-c4bebc00-bfcc-11eb-8df8-0d67bca0a49c.png)

**Comment by ollo69** [comment] 2021-05-28 12:59
This is not an issue, expected behavior in HA control. Already discussed in issue #156

**Comment by geysent** [comment] 2021-07-10 11:22
Hello, I have the samen problem. Room temperature is nut updating in HA. It will update the temperature in HA when I open the LG thinq app.

**Comment by disgustipated** [comment] 2021-07-13 21:40
Same thing, temps are not being updated unless I open the app on my phone and as soon as I do it updates in the hass ui

**Comment by lukas1760** [comment] 2021-07-18 09:32
Hello, I have same problem like geysent. Here is no data updated until I open thinq app on mobile. But still many thanks for your work.

**Comment by ollo69** [comment] 2021-08-02 14:12
Can someone sniff the command sent to LG cloud when ThinQ app is opened? I don't have LG Climate, I cannot fix this without additional info.

**Comment by disgustipated** [comment] 2021-08-02 15:10
Tried to grab a trace using packet capture app but looks like android has changed some things since i last did a packet capture and its having trouble decrypting ssl. might be able to look at this more this afternoon as it seems i have to apply a cert with root.

**Comment by ollo69** [comment] 2021-08-02 15:16
> Tried to grab a trace using packet capture app but looks like android has changed some things since i last did a packet capture and its having trouble decrypting ssl. might be able to look at this more this afternoon as it seems i have to apply a cert with root.

Unfortunately using Android is complex. More simple if you have an Apple device and MitMiProxy

**Comment by ollo69** [comment] 2021-11-07 22:05
Closed this issue, with last release it should be fixed.

**Closed by ollo69** 2021-11-07 22:05 UTC
