### ISSUE TITLE
Stopped working in home assistant retrying setup. Thinq platform not ready.   

### ISSUE THREAD

**Issue by guitarbo1971** [ollo69/ha-smartthinq-sensors#374] opened 2022-08-17 13:45 UTC
**Describe the bug**
If possible attach the JSON info file for your devices.

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed:
 - Component version installed:
 - Last know working version:
 - LG device type and model with issue:
 - LG devices connected (list):

**Output of HA logs**
Paste the relavant output of the HA log here.

```

```

**Additional context**

**Comment by ollo69** [comment] 2022-08-17 14:07
Please provide details as described in issue template

**Comment by guitarbo1971** [comment] 2022-08-17 14:15
Can you tell me what log you need and how to find it?  Sorry for the
newbie questions. I appreciate your help

**Comment by ollo69** [comment] 2022-08-17 14:16
Did you check LG mobile app?

**Comment by guitarbo1971** [comment] 2022-08-17 14:17
Yes, I did.   It's working fine

**Comment by ollo69** [comment] 2022-08-17 14:29
Be sure that there are no new message asking you to accept new TOS

Go to Setting->System-Logs, and check if there are errors in the log.

Go to System->Device and check the error in the integration, eventually attach here a screenshot.

**Comment by guitarbo1971** [comment] 2022-08-17 14:37
This error originated from a custom integration.

Logger: custom_components.smartthinq_sensors
Source: custom_components/smartthinq_sensors/wideq/core_async.py:1290
Integration: SmartThinQ LGE Sensors (documentation, issues)
First occurred: 10:13:52 AM (1 occurrences)
Last logged: 10:13:52 AM

Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line
245, in async_setup_entry
    lge_devices, unsupported_devices = await lge_devices_setup(hass, client)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line
496, in lge_devices_setup
    if not await dev.init_device():
  File "/config/custom_components/smartthinq_sensors/__init__.py", line
372, in init_device
    if not await self._device.init_device_info():
  File "/config/custom_components/smartthinq_sensors/wideq/device.py", line
1000, in init_device_info
    self._model_data = await self._client.model_url_info(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py",
line 1329, in model_url_info
    self._model_url_info[url] = await self._load_json_info(url)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py",
line 1290, in _load_json_info
    encoding = chardet.detect(content)['encoding']
AttributeError: module 'chardet' has no attribute 'detect'

**Comment by ollo69** [comment] 2022-08-17 14:51
What version of HA are using? Did you update recently HA or the component?
This issue was already discussed in issue #353 and was related to a HA issue solved in HA 2022.7.4

**Comment by guitarbo1971** [comment] 2022-08-17 14:54
2022 8.5

**Comment by guitarbo1971** [comment] 2022-08-17 14:55
Updated both

**Comment by ollo69** [comment] 2022-08-17 14:56
Did you try reboot HA at least a couple of time. Look like there are some issue installing dependencies.

**Comment by guitarbo1971** [comment] 2022-08-17 14:57
Probably 10 times

**Comment by guitarbo1971** [comment] 2022-08-17 14:59
You mean in app system restart?

**Comment by ollo69** [comment] 2022-08-17 15:06
The problem is that a dependencies is not properly installed. 
There are 2 options:
1) another custom component installed recently is forcing installation of wrong dependencies version -> try remove that component (or at least provide the list of custom integration that you install so that I can check)
2) The dependencies for some other reason is not installed -> you should try install it manually following work-around suggested in issue #353 

In any case is important identify which upgrade cause the issue and the version that was installed before when everything was working.

**Comment by guitarbo1971** [comment] 2022-08-17 15:11
The last Integration was wyze home integration. Oddly enough I can't delete
it. I hit delete and then restart and it's still there

**Comment by ollo69** [comment] 2022-08-17 15:14
This is a custom integration? Can you provide me the link?

**Comment by guitarbo1971** [comment] 2022-08-17 15:15
I installed it from HACS

**Comment by ollo69** [comment] 2022-08-17 15:22
In that case remove from HACS

**Comment by guitarbo1971** [comment] 2022-08-17 15:43
Did that and restarted twice. Still no luck

**Comment by ollo69** [comment] 2022-08-17 15:52
Are u using HASSOS or a Virtual Env?
In any case try opening a command console and launch the command `pip install chardet` (if you are using virtual env you must activate it)
Reboot HA a see if this solve the issue

**Comment by guitarbo1971** [comment] 2022-08-17 15:52
I removed all HACS integrations except the two LG ones

**Comment by guitarbo1971** [comment] 2022-08-17 15:54
HASSOS. Il try that

**Comment by guitarbo1971** [comment] 2022-08-17 15:58
Tried in terminal and got bash: Pip: command not found

**Comment by ollo69** [comment] 2022-08-17 16:14
My be this can help:
https://community.home-assistant.io/t/how-to-run-pip-commands-from-command-line/263519/3

**Comment by guitarbo1971** [comment] 2022-08-17 16:27
I apologize for my lack of understanding. Are you referring the installing
portainer? It's discontinued??

**Comment by ollo69** [comment] 2022-08-17 16:31
Give me some times. I'm checking if I can replace `chardet` library with `cchardet`. Looks like that this 2 modules sometimes create conflict and second one should be faster.

**Comment by guitarbo1971** [comment] 2022-08-17 16:33
Thank you!

**Comment by ollo69** [comment] 2022-08-17 16:49
Can you try to install version `master` from HACS and check if it works?

**Comment by guitarbo1971** [comment] 2022-08-17 16:58
I'm searching HACS and don't see it. Again I apologize for my ignorance on
this matter. I'm trying to keep up.

**Comment by ollo69** [comment] 2022-08-17 17:06
But you say before that you installed components using HACS!

**Comment by guitarbo1971** [comment] 2022-08-17 17:10
Yes

**Comment by ollo69** [comment] 2022-08-17 17:53
Ok, in any case you can directly install last release (v0.24.1) that contain the change.

**Comment by guitarbo1971** [comment] 2022-08-17 17:56
Can you tell me the steps to do that? Thank you so much

**Comment by guitarbo1971** [comment] 2022-08-17 18:05
Just found it on HACS

**Comment by guitarbo1971** [comment] 2022-08-17 18:06
That fixed it!  Awesome work!

**Comment by ollo69** [comment] 2022-08-17 18:21
Very well. I close this issue.

**Closed by ollo69** 2022-08-17 18:21 UTC

**Comment by guitarbo1971** [comment] 2022-10-11 07:13
Loaded the home assistant version. It seems to be running
