### ISSUE TITLE
sensor "binary_sensor.washer_wash_completed" only activated once

### ISSUE THREAD

**Issue by haigaru** [ollo69/ha-smartthinq-sensors#138] opened 2021-03-27 04:55 UTC
I use the washing machine 2 times every day, I have automation to announce the washing machine is finished on google home speaker and phone. I usually see this sensor notice 1 time, next wash no sensor activated
![Screen Shot 2021-03-27 at 11 53 30](https://user-images.githubusercontent.com/60953672/112710371-24c4b380-8ef3-11eb-8a68-0c66003f5d0d.png)
![Screen Shot 2021-03-27 at 11 54 49](https://user-images.githubusercontent.com/60953672/112710383-4a51bd00-8ef3-11eb-81d9-5fed2f6b48a7.png)

**Comment by haigaru** [comment] 2021-03-27 04:56
Environment (HASSIO, Raspbian, etc): Hassio
Home Assistant version installed: 2021.3.4
Component version installed: v0.6.5
Last know working version:
LG device type and model with issue: WTWS3-FL
LG devices connected (list):

**Comment by KTibow** [comment] 2021-03-27 14:03
What about the history of the main washer entity?

**Comment by haigaru** [comment] 2021-04-02 01:02
![image](https://user-images.githubusercontent.com/60953672/113368710-b74cd300-9389-11eb-9f5f-b88d14b87ca0.png)

**Comment by ollo69** [comment] 2021-04-02 09:30
I see that the sensor became unavailable a couple of time. It is just a case or is a normal behavior?

**Comment by haigaru** [comment] 2021-04-03 03:05
> I see that the sensor became unavailable a couple of time. It is just a case or is a normal behavior?

After updating the new version, the sensor "binary_sensor.washer_wash_completed" does not update after the washing machine completes.
![Screen Shot 2021-04-03 at 10 05 01](https://user-images.githubusercontent.com/60953672/113466215-1c74f700-9464-11eb-8659-180d9adec232.png)
![Screen Shot 2021-04-03 at 10 04 21](https://user-images.githubusercontent.com/60953672/113466217-20087e00-9464-11eb-8293-da035e47f6fa.png)

**Comment by ollo69** [comment] 2021-04-04 20:23
I need more details to understand why sensor become unavailable. Can you provide some logs when this occurs?

**Comment by haigaru** [comment] 2021-04-05 03:05
> I need more details to understand why sensor become unavailable. Can you provide some logs when this occurs?

today I continue to monitor the washing machine, the sensors are working properly. Only the sensor "binary_sensor.washer_wash_completed" did not change state
![image](https://user-images.githubusercontent.com/60953672/113532531-c59f2700-95f5-11eb-86fc-f14a87e50399.png)

![image](https://user-images.githubusercontent.com/60953672/113532661-1f9fec80-95f6-11eb-8a5b-c1daa615ed82.png)

![image](https://user-images.githubusercontent.com/60953672/113532617-039c4b00-95f6-11eb-90cb-0b0f7ed9ced3.png)

I will try reinstalling LG Integrations and watching. I will report back the results soon

**Comment by haigaru** [comment] 2021-04-05 06:23
after I removed and reinstalled LG Integration

![image](https://user-images.githubusercontent.com/60953672/113544093-d5c4ff80-9611-11eb-928c-5cf135a9ed78.png)

![image](https://user-images.githubusercontent.com/60953672/113544216-13c22380-9612-11eb-9845-8e070ee30467.png)

**Comment by ollo69** [comment] 2021-04-05 11:16
When I ask `log` I do not mean `logbook` but the `ha log file`. I need to analyze the cause that change the status of the sensor to `unaivalable`.

**Comment by haigaru** [comment] 2021-04-06 03:39
> When I ask `log` I do not mean `logbook` but the `ha log file`. I need to analyze the cause that change the status of the sensor to `unaivalable`.

2021-04-06 08:57:57 ERROR (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> HttpStatusCode.UNAUTHORIZED
2021-04-06 08:57:57 ERROR (MainThread) [custom_components.hacs] ollo69/ha-smartthinq-sensors - HttpStatusCode.UNAUTHORIZED

2021-04-06 09:27:57 ERROR (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> HttpStatusCode.UNAUTHORIZED
2021-04-06 09:27:57 ERROR (MainThread) [custom_components.hacs] ollo69/ha-smartthinq-sensors - HttpStatusCode.UNAUTHORIZED

2021-04-06 10:27:57 ERROR (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> HttpStatusCode.UNAUTHORIZED
2021-04-06 10:27:57 ERROR (MainThread) [custom_components.hacs] ollo69/ha-smartthinq-sensors - HttpStatusCode.UNAUTHORIZED

**Comment by KTibow** [comment] 2021-04-06 13:38
@haigaru please give all of the log, that bit is just from HACS, and is unrelated. You should probably reinstall HACS so it can be properly authorized, though.

**Comment by haigaru** [comment] 2021-04-06 14:24
[home-assistant.log](https://github.com/ollo69/ha-smartthinq-sensors/files/6265267/home-assistant.log)

Thank you for your help: D

**Comment by KTibow** [comment] 2021-04-06 20:23
You might need to set the log level to debug for the custom component.

**Comment by haigaru** [comment] 2021-04-07 02:10
> You might need to set the log level to debug for the custom component.

@KTibow 
I'm a beginner, please guide me.
my default configuration
logger:
   default: warning

**Comment by KTibow** [comment] 2021-04-07 19:44
```
logger:
  default: warning
  logs:
    custom_component.smartthinq_sensors: debug
```
Correct me if I'm wrong @ollo69.

**Comment by haigaru** [comment] 2021-04-09 11:07
@ollo69 I send you a new log file
[home-assistant (1).log](https://github.com/ollo69/ha-smartthinq-sensors/files/6285266/home-assistant.1.log)

**Comment by ollo69** [comment] 2021-04-09 22:44
I take a look to both your log file, let me say that there are tons on warning and errors related to several component. I think you should clean-up your HA installation, it is really hard to find the cause for your issue that is probably related to conflict caused by bad configuration.
My suggestion is to perform a clean installation of HA and than configure only the integration that you need, monitoring the log to see that error and warning are not present. Probably this will also solve the issue with this integration. If not you can than come back here to analyze what can be wrong.

**Comment by haigaru** [comment] 2021-04-10 10:32
I am reinstalling hassio and installing only the smarthing_sensor component. I'll come back with a new log. Thank @ollo69

**Comment by haigaru** [comment] 2021-04-10 16:20
dear @ollo69 new log
[home-assistant (2).log](https://github.com/ollo69/ha-smartthinq-sensors/files/6290253/home-assistant.2.log)

![Screen Shot 2021-04-10 at 23 15 13](https://user-images.githubusercontent.com/60953672/114276908-f4ccf280-9a52-11eb-90b7-a97bfa090048.png)
![Screen Shot 2021-04-10 at 23 15 36](https://user-images.githubusercontent.com/60953672/114276911-f7c7e300-9a52-11eb-8a6d-872430b61fec.png)

**Comment by ollo69** [comment] 2021-04-10 16:42
Attached log seems just related to the startup of HA. Can you provide log in the period when the wash is completing (and the sensor become unavailable). I need to understand why this is happening. Don't forget to enable debug!

**Comment by haigaru** [comment] 2021-04-10 16:52
@ollo69 : After I finished washing, I took a picture and got the log. I will try downgrading and testing at the same time.

**Comment by ollo69** [comment] 2021-04-10 17:03
Looks like the log  start 1 minute after the time in your log-book. Are you sure you are taking the right log file?

**Comment by haigaru** [comment] 2021-04-10 17:14
@ollo69: I looked at the history and discovered that the washer, error and complete sensor changed to the "Became unavailable" status. you look on the picture
![Screen Shot 2021-04-11 at 00 10 38](https://user-images.githubusercontent.com/60953672/114278609-d23ed780-9a5a-11eb-99b8-99d7a16d8606.png)
![Screen Shot 2021-04-11 at 00 10 57](https://user-images.githubusercontent.com/60953672/114278611-d4a13180-9a5a-11eb-8546-815d45829632.png)
![Screen Shot 2021-04-11 at 00 11 06](https://user-images.githubusercontent.com/60953672/114278614-d79c2200-9a5a-11eb-9b1c-3c647a827fd2.png)

**Comment by ollo69** [comment] 2021-04-10 17:46
@haigaru, it is not necessary (and not polite) that you mention me on every comment. I will be notified in any case.

It is normal that all sensors become unavailable and not only wash completed, they are connected to the same refresh method. But I need to understand why this happen and for this I need the log file that cover the period when the problem occur.

**Comment by ollo69** [comment] 2021-04-10 21:41
I analyze better the history, let me say this;

1) The 3 sensors become unavailable because probably at that moment you enabled all the others, right? This is a normal behavior, HA disable all sensors related to the devices before enabling new ones.

2) At about 11.10, your wash program completed, but from what I can see it doesn't move to "ended" state  because `pre_state` become "spinning". In this case it is normal that `wash_completed` is not activated, because it checks for state "ended" in `run_state` or `pre_state`. I don't know if this is related to that program, probably you should use a more complete washing program for tests.

**Comment by igorsantos07** [comment] 2021-04-25 22:01
So... Today I ran two different programs on my washer/dryer combo machine, and noticed different results for each of them:
1. I ran a washing program until the end, and it does _not_ show a "complete" state - it goes from centrifuge to `-`. At that point the LG app notified me, and the machine turned off.
2. I turned it on again, took some clothes and left the rest in a drying program, but in the end, it enters a "slow tumble" never-ending cycle (showing "Cd" on the screen), which identifies in the run state as "cooling". However, between drying and cooling it DOES show as "completed" for a couple of seconds, which is what the integration looks for, I guess?

![washing-state](https://user-images.githubusercontent.com/532299/116010899-3edbd980-a5f8-11eb-9376-3c83224bf5a2.png)
_(Open to see the details. I wrote the parts inside the graph that are in English)_

> Is it possible to filter the History screen by integration or device, instead of a single entity? I had to use gimp to group these lol

**Comment by ollo69** [comment] 2021-04-28 22:20
What about "previous state"?

**Comment by igorsantos07** [comment] 2021-05-02 17:43
Did some digging and found that entity disabled :sweat_smile: Is that a severe mistake? I'm not sure but I guess I might have disabled a bunch of entities upon initial HA configuration? hahaha

**Comment by ollo69** [comment] 2021-05-02 18:49
> Did some digging and found that entity disabled 😅 Is that a severe mistake? I'm not sure but I guess I might have disabled a bunch of entities upon initial HA configuration? hahaha

Many entity are disabled by default. But you need to enable to monitor values and better analyze behavior.

**Comment by igorsantos07** [comment] 2021-05-03 04:02
Haha cool, then! I'll keep an eye on it next time.

**Comment by ollo69** [comment] 2021-06-12 10:35
Close this thread because no feed-back from more than one month. Open new one if still have issue.

**Closed by ollo69** 2021-06-12 10:35 UTC
