### ISSUE TITLE
HA update from 2023.9.x to 2024.2.1 throws warnings - LG Minisplit AC

### ISSUE THREAD

**Issue by VentureRider** [ollo69/ha-smartthinq-sensors#699] opened 2024-02-12 17:48 UTC
**Describe the bug**

Warnings in the log file.  JSON attached.

[smartthinq_sensors-ba58b109e4196618a3fc4418154e559b-iCool-3ed09d33de8ae87c7b8057b3a51afff6.json](https://github.com/ollo69/ha-smartthinq-sensors/files/14244700/smartthinq_sensors-ba58b109e4196618a3fc4418154e559b-iCool-3ed09d33de8ae87c7b8057b3a51afff6.json)

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Environment details:**
 - Environment (HASSIO, Raspbian, etc):
 - Home Assistant version installed:
 - Component version installed:
 - Last know working version:
 - LG device type and model with issue:   

 - LG devices connected (list):
 - 
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/125074226/5edbaa3c-3d5a-497f-8933-e45be39b9cb1)

**Output of HA logs**

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climate (documentation, issues)
First occurred: 12:25:29 PM (6 occurrences)
Last logged: 12:36:47 PM

Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

Entity None (<class 'custom_components.smartthinq_sensors.climate.LGEACClimate'>) implements HVACMode(s): off, heat, dry, cool, fan_only, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/ollo69/ha-smartthinq-sensors/issues

**Additional context**

**Comment by ollo69** [comment] 2024-02-12 19:09
Closed as duplicate of #692

**Closed by ollo69** 2024-02-12 19:09 UTC

**Comment by VentureRider** [comment] 2024-02-12 19:34
My apologies for posting a duplicate.

**Comment by ollo69** [comment] 2024-02-12 19:36
No problem, thanks👍
