### ISSUE TITLE
Washing machine - run completed not update

### ISSUE THREAD

**Issue by Keany** [ollo69/ha-smartthinq-sensors#695] opened 2024-02-09 14:00 UTC
Hello, 

last versions binary_sesnsor entity Run completed doesnt work for Washing Machine.

![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/246199/63519d54-bd6a-42b8-939b-2b8b46857269)

![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/246199/e5ead6dc-101e-43bd-88c2-c732da4e5907)

Plugin version 0.38.0

HA: 
Core
2024.2.0
Supervisor
2024.01.1
Operating System
11.5
Frontend
20240207.0

**Comment by ollo69** [comment] 2024-02-09 14:08
There are no change in this last about that sensor!!!!
Please provide detail about your issue. Provide log, diagnostics and information about difference between expected behavior.
Does not work is not enough.

**Comment by Keany** [comment] 2024-02-09 14:32
Expected: after run completed of washing machine there should be binary_sensor for several sec on, but now is still off. 

This error is not related to the latest version, for me it was not working about 3 versions back. 

I turned logging on now for more data. 

For Dryer it is working fine. 

For example: 
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/246199/2189022e-3b74-4502-885e-2ff0b5d02248)

Washing machine: 
![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/246199/7ae4938a-7f33-4ec8-9c8b-356776b68226)

Diagnostic:
[smartthinq_sensors-d773923c731a7bddbd1b879f705e5d51-PRAČKA-ec6df405829df634f62870bef921295d.json](https://github.com/ollo69/ha-smartthinq-sensors/files/14222882/smartthinq_sensors-d773923c731a7bddbd1b879f705e5d51-PRACKA-ec6df405829df634f62870bef921295d.json)

**Comment by ollo69** [comment] 2024-02-09 15:10
Ok, here is a more clear context, we can analyze this.
First of all please consider that run completed is a calculated sensor and is not provided by device.
The check done is comparing `run state` and `pre state`, so the first think to analyze is: what are the status for this 2 sensors on your washer machine when `run_completed` should be on? Can you check and provide this information?

**Comment by Keany** [comment] 2024-02-11 09:46
run state and pre state was washing, rinsing. but run completed is still off.

Log: 
[home-assistant_2024-02-11T09-44-02.223Z.zip](https://github.com/ollo69/ha-smartthinq-sensors/files/14231892/home-assistant_2024-02-11T09-44-02.223Z.zip)

**Comment by Keany** [comment] 2024-02-11 09:51
![IMG_0762](https://github.com/ollo69/ha-smartthinq-sensors/assets/246199/d0c1067f-be44-4866-a89d-56c0ef6c3627)
![IMG_0763](https://github.com/ollo69/ha-smartthinq-sensors/assets/246199/32f85dde-7c65-4597-b832-14f65cf2e3df)

**Comment by ollo69** [comment] 2024-02-11 10:30
Problem here is that your device always return same value for `run_state` and `pre_state`. I will think about a possible solution for this case...

**Comment by ollo69** [comment] 2024-02-11 22:05
Please try last release, now `pre_state` is calculated when equal to `run_state`. Not sure if this work, because in any case your device should go in END state that I don't see in your logs.

**Comment by Keany** [comment] 2024-02-15 09:16
I tried last release but no change.

![image](https://github.com/ollo69/ha-smartthinq-sensors/assets/246199/42f9922d-47fb-437b-a9f6-257cb7bea3e2)

[home-assistant_2024-02-15T09-14-50.169Z.log](https://github.com/ollo69/ha-smartthinq-sensors/files/14294015/home-assistant_2024-02-15T09-14-50.169Z.log)

**Comment by ollo69** [comment] 2024-02-15 10:10
As I see from your image there is a big change, `run_state` and `pre_state` are not equal anymore. I do not understand the meaning of what is written, but what are the value (in english) of `pre_state` and `run_state` when wash is completed?

**Comment by Keany** [comment] 2024-02-15 10:24
pre_state is spinning and run state is standby mode

**Comment by ollo69** [comment] 2024-02-15 10:56
So your device go directly from spinning to standby when it complete the cycle? There are no "END" state?

**Comment by Keany** [comment] 2024-02-15 12:45
Yes, there is no "END"

Today: 

sensor.pracka_pre_state,Pohotovostní režim,2024-02-15T07:50:03.329Z    - STANDBY
sensor.pracka_pre_state,Vážení,2024-02-15T07:50:33.331Z  - Weighing
sensor.pracka_pre_state,Praní,2024-02-15T07:51:03.337Z - Washing
sensor.pracka_pre_state,Přerušení,2024-02-15T07:52:33.345Z - Paused (small child :D) 
sensor.pracka_pre_state,Praní,2024-02-15T08:19:33.344Z - Washing
sensor.pracka_pre_state,Máchání,2024-02-15T08:39:03.352Z -  - Rinsing
sensor.pracka_pre_state,Odstřeďování,2024-02-15T08:49:03.353Z - Spinning

And thats all.

**Comment by ollo69** [comment] 2024-02-18 16:01
Please try last release and let me know if it works. I implemented some logics based on states and remaining time, not so perfect but I don't see other options for this case...

**Comment by Keany** [comment] 2024-02-18 20:39
I tried and looks more better. Bur one thing. Now is Run completed ON forever. For dryer only 30sec. Look on screenshots.

![IMG_0819](https://github.com/ollo69/ha-smartthinq-sensors/assets/246199/4726705b-8572-4fcb-abad-ed14bec37093)
![IMG_0818](https://github.com/ollo69/ha-smartthinq-sensors/assets/246199/467cf4e8-a13c-46cb-8b11-7a96945ebada)

**Comment by ollo69** [comment] 2024-02-18 20:49
Need a list of status change and remain time information for both devices when run completed is triggered and than deactivated

**Comment by Keany** [comment] 2024-02-20 07:17
[dryer run state.csv](https://github.com/ollo69/ha-smartthinq-sensors/files/14340761/dryer.run.state.csv)
[dryer run completed.csv](https://github.com/ollo69/ha-smartthinq-sensors/files/14340762/dryer.run.completed.csv)
[dryer remain time.csv](https://github.com/ollo69/ha-smartthinq-sensors/files/14340763/dryer.remain.time.csv)
[run completed washing machine.csv](https://github.com/ollo69/ha-smartthinq-sensors/files/14340764/run.completed.washing.machine.csv)
[pre state washingmachine.csv](https://github.com/ollo69/ha-smartthinq-sensors/files/14340765/pre.state.washingmachine.csv)
[runstate washing.csv](https://github.com/ollo69/ha-smartthinq-sensors/files/14340766/runstate.washing.csv)
[remaintime washingmachine.csv](https://github.com/ollo69/ha-smartthinq-sensors/files/14340767/remaintime.washingmachine.csv)

**Comment by ollo69** [comment] 2024-02-20 07:36
I suppose that pernamently means until cycle is started again and have to be considered correct behavior

**Comment by Keany** [comment] 2024-02-20 07:39
Yes it looks like that, I thought that binary run completed only means a short pulse at the end of the cycle for example 1-30s and then it is off again.

So this is currently the correct behavior?

**Comment by ollo69** [comment] 2024-02-20 08:00
Yes, run completed should go on when a cycle is completed and should stay on until you do something with device, like turn it on to start a new cycle, that would set turn completed off.
Anyway I'm making a last review that will be released shortly, thanks for details on states

**Comment by ollo69** [comment] 2024-02-20 11:31
Please test last release and let me know if `run_completed` works as expected / descripted.

**Comment by ollo69** [comment] 2024-02-21 13:00
I close this because duplicated of #226. Please comment on that in case of issue.

**Closed by ollo69** 2024-02-21 13:00 UTC
