### ISSUE TITLE
Energy monitoring

### ISSUE THREAD

**Issue by tismofied** [ollo69/ha-smartthinq-sensors#384] opened 2022-09-18 16:23 UTC
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Add Dryer Energy monitoring attribute to the integration.

**Describe alternatives you've considered**

**Additional context**
Would love to be able to add dryer Energy monitoring and number of cycles attributes of the dryer to Home Assistant.

Options shown in the LG App.

![image](https://user-images.githubusercontent.com/90809124/190917415-c2933215-9a98-409f-9ece-cbe482554c54.png)

![image](https://user-images.githubusercontent.com/90809124/190917431-409bbd17-4ccc-490e-a591-5e263cca07e1.png)

Number of weekly cycles:

![image](https://user-images.githubusercontent.com/90809124/190917437-a71dad0e-0447-4a93-a93b-c07af21558a4.png)

**Comment by yurkuz** [comment] 2022-11-02 20:24
It is very strange that this function has not yet been implemented in HA!  Moreover, this function is in the position of LG ThinQ.  However, the values ​​are not shown.  But still, I would like to see this feature in device integration!

**Comment by AngellusMortis** [comment] 2022-11-16 02:41
Probably a dupe of https://github.com/ollo69/ha-smartthinq-sensors/issues/309

**Comment by MetalfanBlackness** [comment] 2022-12-17 19:59
For energy monitoring wouldn't it be better to (first) adjust the energy entity to enable usage in the energy dashboard:
https://www.home-assistant.io/docs/energy/individual-devices/

**Comment by ollo69** [comment] 2022-12-17 22:06
All this energy monitor provided by this kind of devices (dryer, washer, etc.), are only statistic values based on the used program and not a real information of energy used. I checked the payload of the devices, there is not a real time energy consumption expressed in W (like devices as AC or Water-Heater provide), but only some table that say program X = energy X. For this reason does not make sense implement this kind of sensor, it is better to just attach a cheap smart plug with energy monitor function to have really more accurate values. And yes, this is duplication of #309 and some others.

@MetalfanBlackness,

not really understanding your point. Devices that have energy meter (as AC or Water-Heater mentioned before) provide energy power sensors expressed in W, This sensors can be used by the integration that you mention to obtain the long term statistics in HA.

**Comment by MetalfanBlackness** [comment] 2022-12-19 22:17
I don't think I understand the issue correctly. I was saying the energy dashboard can already show you how much energy a device uses on a daily basis (and weekly etc etc). For me my LG AC using this plugin is not available to add to the energy dashboard as a individual device.

**Comment by ollo69** [comment] 2022-12-20 00:04
> For me my LG AC using this plugin is not available to add to the energy dashboard as a individual device.

Why not? Isn't the power sensor available?

**Comment by KrzysztofHajdamowicz** [comment] 2022-12-27 09:22
> I don't think I understand the issue correctly. I was saying the energy dashboard can already show you how much energy a device uses on a daily basis (and weekly etc etc). For me my LG AC using this plugin is not available to add to the energy dashboard as a individual device.

What @ollo69 wanted to say, this device have not real energy metering. Device has some pre-determined values (lookup table, if value X then consumption is A, Y->B, Z->C). This mean that such sensor doesn't show true value of energy used, it is just an approximation.
Same thing you can achieve with powercalc integration.

**Comment by tismofied** [comment] 2022-12-27 15:09
Thank you for the explanation!

**Closed** 2022-12-27 15:10 UTC
Labels: Feature Request
