### ISSUE TITLE
LGE Washer: Invalid Login info!

### ISSUE THREAD

**Issue by katerry** [ollo69/ha-smartthinq-sensors#3] opened 2020-03-28 02:28 UTC
I am receiving the following error in the log after I submit the access token:

Log Details (ERROR)
Logger: custom_components.smartthinq_washer.config_flow
Source: custom_components/smartthinq_washer/config_flow.py:67
First occurred: 10:23:30 PM (2 occurrences)
Last logged: 10:25:06 PM

LGE Washer: Invalid Login info!

**Comment by ollo69** [comment] 2020-03-28 02:35
Are you sure that your token is correct?
Did you put the right value for region and language associated to your account?

**Comment by katerry** [comment] 2020-03-28 03:08
I am certain. Region US Language en-US.  I am able to login just fine and once I submit the redirection URL I get a access token but one I submit it I get Invalid SmartThinQ credentials.

**Comment by towerhand** [comment] 2020-03-28 03:33
I left the token empty on the first window when setting up the integration, then followed the directions on the next step to get a new token and it worked for me.

**Comment by ollo69** [comment] 2020-03-28 09:25
This is strange and hard to investigate. Can you try, just for check, to save your generated token, than close the browser, re-open it and perform the configuration using the token previously saved?

**Comment by katerry** [comment] 2020-03-28 13:30
I am not sure what the issue is. I followed your instructions but no change. I even reset the password and confirmed that when I sign into the APP they work. When I sing into the Smartthinq login URL I just get a blank screen. Is that normal?

**Comment by ollo69** [comment] 2020-03-28 13:41
Blank screen is normal, that login only redirect you to a page from where you can take a refresh token.
It is possible that the hardware where Home Assistant run have some internet connection limit or that some firewall are enabled?

**Comment by katerry** [comment] 2020-03-28 13:54
I use pIhole but I just disabled it and tested again with the same result.

**Comment by katerry** [comment] 2020-03-28 14:12
I am sure that the credential work because when I use wideq I get the following output:

![image](https://user-images.githubusercontent.com/42949646/77824953-9994c000-70dc-11ea-93f6-f670083d69de.png)

**Comment by ollo69** [comment] 2020-03-28 14:33
Can you retry with my last commit? I increased timeout, maybe I set it it too low.
Should work because wideq call are the same you are using.

**Comment by katerry** [comment] 2020-03-28 14:47
Just retried with the same result. Here is the build I am using:
![image](https://user-images.githubusercontent.com/42949646/77825703-73bdea00-70e1-11ea-97ee-0cf7ea4375ac.png)

**Comment by ollo69** [comment] 2020-03-28 14:53
The PC from where you are launching the test is the same where you run HA?
Can you attach here in a zip with the wideq version that you are using for test, just to be sure that there are no difference?

**Comment by katerry** [comment] 2020-03-28 15:00
I run HA using a raspberry pi 3 under HASSIO. I am running wideq under Ubuntu on my pc. The wideq zip is from the following link:

https://github.com/sampsyo/wideq/archive/master.zip

**Comment by ollo69** [comment] 2020-03-28 15:07
Ah, ok HASSIO is the problem, it have some limitation and I think do not support request.
You should check [this post](https://community.home-assistant.io/t/requests-library-in-python/40089) or maybe search other info on the web  to see if it is possible to enable it.
I  revert timeout as original.
Please report here if you discover some solutions.

**Comment by kenmaples** [comment] 2020-03-28 20:00
I am also running into this issue on Home Assistant (used to be called HASSIO). Does this code base support the thinq API v2?

**Comment by towerhand** [comment] 2020-03-28 20:14
I’m running the latest version of Home Assistant, installed hassio VM container on proxmox and this custom integration is working for me. Installed it via HACS with a new token.

**Comment by ollo69** [comment] 2020-03-30 15:45
Can I close this issue? I have no way for the moment to manage the component working on HASSIO.

**Comment by katerry** [comment] 2020-03-30 15:57
Thanks for your effort. FYI I created an X86 Docker Home Assistant and added HACS and your custom component with the same result so this issue is not limited to HASSIO. Maybe LG is setting up new accounts different? I just setup my Washer and Dryer last month.

**Comment by ollo69** [comment] 2020-03-30 16:08
Thanks, for closing issue. In any case I will do some test with an HASSIO installation to better understand if is the issue is in the component or related to LG account. I will keep you informed.

**Comment by ollo69** [comment] 2020-03-30 20:01
Hi, 
I just finish to make a test now using HASSOS, I installed it from scratch, added HACS and then istalled the component. It works without any issue.
The point is that, if you are able to connect with the test program, you should also be able to connect with the component because they use the sami API call.
I reopen this issue, need to understand where is the problem.

**Comment by katerry** [comment] 2020-03-30 21:24
I can email you my redirect URL If you would like.

**Comment by ollo69** [comment] 2020-03-30 21:39
This could help, but wait, before I want to do other tests. 
I will ask you if I will don't find anything.

Thx.

**Comment by kenmaples** [comment] 2020-03-30 21:47
There has been a good deal of conversation around the new API on the thread from the original source of wideq - https://github.com/sampsyo/wideq/issues/46

**Comment by ollo69** [comment] 2020-03-30 22:49
Ok, i will analyze better this API v2, but I understand that katerry run test application with API v1 and is able to connect to the washer, am I right?
Who is already succesfully using API v2?

**Comment by ollo69** [comment] 2020-03-31 00:53
I did some test, creating a new LG account with language en-US. It was failing, but because there are no device associated. My suspect is that some error is preventing process to end, but at this point I need to try with your token.
If you can please e-mail me your redirect URL at "aolivero@gmail.com".

Thx.

**Comment by katerry** [comment] 2020-03-31 00:58
I just emailed you my redirect.

**Comment by daveonkels** [comment] 2020-03-31 01:10
I'm still in the same boat - fully auth'd but no devices being returned. Sending you my redirect as well @ollo69

**Comment by AbsoluteMidnight** [comment] 2020-03-31 10:20
Hello! I have the same problem, i get "Invalid SmartThinQ credentials." following the UI. I tried editing configuration.yaml too, but after restarting Hassio warns me i have a new device in integrations page, but asks me to configure it and the link gets me to the same UI with the same error message.

**Comment by ollo69** [comment] 2020-03-31 18:00
Hi,

I have some news. 
Seems that in some case there is a problem with TLS version, so I set to V1.0. This is probably related to the version of python so behavior of test program ran on different server may change.
In any case I executed tests with both tokens:
- **katerry**: unfortunatly with your token I always receive back an "internal server error" (you should see these error in the log now). You should try to generate a new one.
- **daveonkels**: with modification now I'm able to connect, but from your token I just receave a dishwsher (that is not managed at the moment)

To install this version please select the version "master" because I still not released a official version.

Waiting for your feedback.

**Comment by kenmaples** [comment] 2020-03-31 18:10
I know that my devices are on the newer API, but though I would still report in.

I just tested with master and still get the invalid login:
Log Details (ERROR)
Logger: custom_components.smartthinq_washer.config_flow
Source: custom_components/smartthinq_washer/config_flow.py:84
First occurred: 11:05:31 AM (1 occurrences)
Last logged: 11:05:31 AM

LGE Washer: Invalid Login info!

**Comment by ollo69** [comment] 2020-03-31 18:15
Can you make the test using the last version from "master" repository and not the last release. You should probably have an additional error in the log.
Can you confirm that API v2 released [here](https://github.com/gladhorn/wideq) are working for you?

**Comment by kenmaples** [comment] 2020-03-31 19:12
Perhaps I am doing something wrong, but I pulled master again and setup the integration again. Log reports the same.

I can confirm with https://github.com/gladhorn/wideq I am able to list my devices (washer & dryer).

**Comment by ollo69** [comment] 2020-03-31 19:22
You should see another error before... but don't care.

**Comment by MattL0** [comment] 2020-03-31 23:13
I have managed to get the values to Homeseer like that (see the two last posts from me ) 
https://forums.homeseer.com/forum/lighting-primary-technology-plug-ins/lighting-primary-technology-discussion/lg-smartthinq-xboxmeister/1338868-plans-for-lg-washer-dryers


My nodered flow have been update since that,.... so I also get the remaining time in minutes .

**Comment by AbsoluteMidnight** [comment] 2020-04-01 14:33
Hi again, i reply here to the questions you asked me in the commit (sorry if i posted there).

> are you sure you are running last version (how you install it)?

I guess so, i installed it using HACS who warned me about a new version. Then i also modified the wideq.py with the fix.

> what is your environment (Harsware, OS, version of HA...)

I'm using Hassio (0.107.7) on a Raspberry pi4, with: 
os_name | Linux
os_version | 4.19.106-v8
python_version | 3.7.7

> what info do you fill in the setuo screen?

Region: IT
Language: it-IT
Token: empty field

> are you able to create the new token?

Yes, the UI opened the LG login page, i logged in and got redirected. With that URL the UI were able to fill the token field and after that i received the "Invalid SmartThinQ credentials." error.

If you need anything else, i'm here :) thank you!

**Comment by ollo69** [comment] 2020-04-01 14:43
Do you receave the error immediatly or it take some time?
Can you zip and attach here your log file?
If you don't care and you can send me (via e-mail) the redirect URL I can perform some additional test...

**Comment by AbsoluteMidnight** [comment] 2020-04-01 14:54
> Do you receave the error immediatly or it take some time?

I would say about 3 seconds, but my internet connection is not so fast, so maybe it can slow it down a bit. 

> Can you zip and attach here your log file?

I don't know if there is a bigger log file, in the one i can see in HA i just read:

"Logger: custom_components.smartthinq_washer.config_flow
Source: custom_components/smartthinq_washer/config_flow.py:84 
First occurred: 16:23:25 (2 occurrences) 
Last logged: 16:48:52

LGE Washer: Invalid Login info!"

Where is the file, so i can get it? (Sorry, i'm just starting with this stuff)

> If you don't care and you can send me (via e-mail) the redirect URL I can perform some additional test...

Yes, of course. Do i find your e-mail address in your profile here on github?

Thanks again!

**Comment by ollo69** [comment] 2020-04-01 15:13
Write to aolivero@gmail.com.
For the log file, in HA config directory you should have a file called homeassistant.log.
If you find it,, you can send it attached to the e-mail.

**Comment by ollo69** [comment] 2020-04-01 16:46
I tested your token. It work properly, but do not retrieve any device, for this reason send you back the error. I have to correct the message in this case.
Are you sure that you have devices registered with ThinQ app?

**Comment by AbsoluteMidnight** [comment] 2020-04-01 16:48
> Are you sure that you have devices registered with ThinQ app?

Yes, i added it at the beginning of February, i can see in my account on LG website. Maybe it doesn't use the same database?

**Comment by AbsoluteMidnight** [comment] 2020-04-01 16:59
> Are you sure that you have devices registered with ThinQ app?

![photo_2020-04-01_18-58-26](https://user-images.githubusercontent.com/59233746/78164954-e2d17080-744a-11ea-8e65-5e0998d739a6.jpg)

**Comment by ollo69** [comment] 2020-04-01 17:03
I think that this is something related to the APIv2. Probably they are moving to new account, and old API provide back empty list. 
I Have to work on this....

**Comment by AbsoluteMidnight** [comment] 2020-04-01 17:08
> I think that this is something related to the APIv2. Probably they are moving to new account, and old API provide back empty list.
> I Have to work on this....

OK, solved! Don't know how it's possible. I logged out from the app and logged in again and the washer wasn't there, so i added it again and now the component finds it.

**Comment by ollo69** [comment] 2020-04-01 17:14
Interesting... maybe other with same issue can try same step.
I will write this on redme and I will fix the code to not give error if no device are available.

**Comment by tayanov** [comment] 2020-04-05 08:01
I have login incorrect too. Need use APIv2. With v2 i see washer. with v1 not.

**Comment by ollo69** [comment] 2020-04-05 13:18
Working on APIv2, it take some time. Stay tuned...

**Comment by ollo69** [comment] 2020-04-06 22:22
I have implemented API v2 based on available projects on the web, unforturtunatly it is not possible (at least at moment) read the device states. With my account I'm able to read the devices list, but state command is not implemented at all. I'm just able to see, with the device list json received during initial connection, a generic "deviceState".
During initial setup you can select API to use, please make some tests and post here your feed-back and possible suggestion.
In any case i'm not conviced that this APIv2 are really required. Also IFTT still use old login page (and so old API). First test is to not login using social media account, if you are using this kind of login.

P.S. the implemented code review will make simple add new devices management.

**Comment by daveonkels** [comment] 2020-04-06 22:36
@ollo69 - I spoke too soon in my last comment on #2 . I recreated my account using a non-social media login and thought I was successful with your most recent v1 API but could never get a device returned. I just tested out your v2 API version and it worked which tells me there must be something different about the way new accounts are being created. Not sure if the age of the washer matters but the device I have was purchased < 6 months ago.

<img width="388" alt="lgwasher" src="https://user-images.githubusercontent.com/533642/78611623-38779580-781c-11ea-9eed-603fedd265f3.png">

**Comment by ollo69** [comment] 2020-04-06 22:43
So now you have a device but you don't have the state for this, right?
Hope that some additional info come to be able to get device status also with APIv2....

**Comment by daveonkels** [comment] 2020-04-06 23:38
Correct - test ran the washer and can confirm that no status data is flowing through. If it's helpful I can get you my token and we can coordinate a time where I start a cycle on the machine.

**Comment by kenmaples** [comment] 2020-04-06 23:50
Using api2, I am now able to pull the washer. My washer does not receive updates, and my dryer does not show up. Both as expected at this point.

**Comment by ollo69** [comment] 2020-04-06 23:57
> Correct - test ran the washer and can confirm that no status data is flowing through. If it's helpful I can get you my token and we can coordinate a time where I start a cycle on the machine.

Unfortunatly for the moment this is not usefull. What is unknown is the base API required to poll the machine status. Some reverse enginering or documentation is required to go ahead,

**Comment by daveonkels** [comment] 2020-04-07 00:14
Doubt it will work but I submitted a developer application via the ThinQ developer portal. 
<img width="997" alt="Screen Shot 2020-04-06 at 5 13 43 PM" src="https://user-images.githubusercontent.com/533642/78616755-ffdeb880-7829-11ea-9af8-b73f7b7bfade.png">

**Comment by tayanov** [comment] 2020-04-07 05:26
> Сомневаюсь, что это сработает, но я подал заявку для разработчиков через портал разработчиков ThinQ.
> <img alt="Снимок экрана 2020-04-06 в 5 13 43 вечера" width="997" src="https://user-images.githubusercontent.com/533642/78616755-ffdeb880-7829-11ea-9af8-b73f7b7bfade.png">

I try request api from opensourse community. Lg return denied. But lg work with company only. Api need request from any company. Who make programm and other. With brand and site. Lg love money)).

New apiv2 really not have monitor. And no have full functionality (((

**Comment by tayanov** [comment] 2020-04-07 05:38
Try update. Can add washer. With new apiv2. See name and mac. But not see any sensors...

**Comment by ollo69** [comment] 2020-04-07 13:59
With last release now I'm able to read state from device.
I understood that it is possible to use APiv1 with new authentication, so I'm not sure that is working for all.
Please report your feedback.

**Comment by towerhand** [comment] 2020-04-07 14:06
Do I have recreate the integration?

**Comment by ollo69** [comment] 2020-04-07 14:07
If you want to use APIv2, yes

**Comment by towerhand** [comment] 2020-04-07 14:13
Mine is working great as it is but I’ll recreate to help testing. Thanks.

**Comment by tayanov** [comment] 2020-04-07 14:30
Installed the latest version of integration. Added a typewriter. I see it MAC address again. Turned on the washing machine. But the sensors show zeros on and off

**Comment by ollo69** [comment] 2020-04-07 14:36
You see any information in the log? Please try to set debug log level for the component adding this rows in configuration.yaml and then post the result or attach the log file.

```
logger:
  default: warning
  logs:
    custom_components.smartthinq_washer: debug
```
Thanks

**Comment by tayanov** [comment] 2020-04-07 14:41
Generic Wideq Error - [('0009', '장치가 존재하지 않습니다.')]. Exiting

**Comment by towerhand** [comment] 2020-04-07 14:52
Set up the integration with the V2, for me it seems to work the same as it used to with V1. For testing I just turned on the washer and changed the settings to see if the changes reflect in HA. There seem to be a 60 sec. polling time. Can you reduce the poling when the washer is on and leave the 60 secs when the washer is off?

When adding the integration the link sent me to a kr.m.lg site too. I'm assuming that's normal.

**Comment by ollo69** [comment] 2020-04-07 14:54
Polling is 30 sec, but when you turn on it take some more time to detect the change (I think is related to comunication between with LG server). I cannot change polling time in runtime.

**Comment by ollo69** [comment] 2020-04-07 14:58
> Generic Wideq Error - [('0009', '장치가 존재하지 않습니다.')]. Exiting
> 
> why korean?)) i set ru-RU RU local
> 
> I have LG frige and washer. Frige work with api1. But not have integration.
> Washer have integration but not have work API ((((

Additional device will come in the future, now I'm trying to manage comunication protocol,
I think that new devices do not comunicate with APIv1. 
If you could provide debug log should be better for analysys.

**Comment by tayanov** [comment] 2020-04-07 15:01
> > Generic Wideq Error - [('0009', '장치가 존재하지 않습니다.')]. Exiting
> > why korean?)) i set ru-RU RU local
> > I have LG frige and washer. Frige work with api1. But not have integration.
> > Washer have integration but not have work API ((((
> 
> Additional device will come in the future, now I'm trying to manage comunication protocol,
> I think that new devices do not comunicate with APIv1.
> If you could provide debug log should be better for analysys.

ofcourse. im ready to help. but how. what needed. 

`Generic Wideq Error - [('0009', '장치가 존재하지 않습니다.')]. Exiting`

its all debug log what i ma see.

**Comment by ollo69** [comment] 2020-04-07 15:08
No, this is an error log. You should change configuration.yaml with info provided before and you will have a lot of debug messge in the log file.

**Comment by towerhand** [comment] 2020-04-07 15:15
did you restart home assistant after adding the debug to the configuration.yaml?

```logger:
  default: warning
  logs:
    custom_components.smartthinq_washer: debug
```

**Comment by tayanov** [comment] 2020-04-07 15:20
> did you restart home assistant after adding the debug to the configuration.yaml?
> 
> ```
>   default: warning
>   logs:
>     custom_components.smartthinq_washer: debug
> ```

yeah. ready
https://pastebin.com/Axy4pPtw

**Comment by towerhand** [comment] 2020-04-07 15:29
You might want to remove that since it has your token and send it to his email.

**Comment by ollo69** [comment] 2020-04-07 15:32
Thanks, this confirm my suspect. 
Call to your API backend "https://ruic.lgthinq.com:46030/api" return a generig 0009 error for your device.
Just one more question: is your account registerd with social network (google, amazon, etc) or you create indipendent account?

As suggested by @towerhand remove the link because contain your token. You can also remove debug option from configuratio.yaml now.

**Comment by tayanov** [comment] 2020-04-07 15:37
> Спасибо, это подтверждает мой подозреваемый. Обратитесь к своему бэкэнду
> API « https://ruic.lgthinq.com:46030/api » и верните ошибку 0009 на ваше устройство.
> Еще один вопрос: ваша учетная запись зарегистрирована в социальной сети (Google, Amazon и т. Д.) Или вы создаете независимую учетную запись?
> 
> В соответствии с предложением @towerhand удалите ссылку, так как содержат ваш токен. Вы также можете удалить опцию отладки из configuratio.yaml сейчас.

offtopic: i try remove token but they is more and diffrent. i remove pastebin.

My lg account is old. from 2012year.  email and pass.

**Comment by ollo69** [comment] 2020-04-07 15:58
API is available, but i think is not used by your washer. Your washer is new?

**Comment by tayanov** [comment] 2020-04-07 16:10
> API is available, but i think is not used by your washer. Your washer is new?

2 month. in russian commynity man buying Dishwasher about 1 month.
and his Dishwasher work over api1.
My frige over 1 year. api1 too.

Time and old or new it is not give understanding.

**Comment by ollo69** [comment] 2020-04-07 16:18
Maybe is model year that is newer?

**Comment by ollo69** [comment] 2020-04-07 18:05
Just to make a quick recap:
- at this moment the component is able to use new authentication and to monitor device based on APIv1 with new authentication model
- based on my reseach on the web, APIv2 is using MQTT. The most advanced project seems to be this: [https://github.com/tinkerborg/wideq](https://github.com/tinkerborg/wideq). 
- I don't have device that use APIv2 so I'm not able to collaborate with this project. 
- hoping that this will enable status polling with APIv2, next step will be integrate this part and find a way to use correct status poll depending on the device.

**Any suggestion / help / PR are welcome.**

As next step I will concentrate on adding other devices to the HA sensor, this of course will require support for test because I only own a washer.

**Comment by tayanov** [comment] 2020-04-07 18:22
And good and bad. I am ready support test frige if you need this))

**Comment by kenmaples** [comment] 2020-04-07 18:52
Any plans on sending PRs back to the original wideq (https://github.com/sampsyo/wideq) or ha component (https://github.com/sampsyo/hass-smartthinq)? That may help to expand the number of testers. Personally I have a washer and dryer on APIv2, and will help testing anyway I can.

**Comment by towerhand** [comment] 2020-04-07 18:54
I have a dryer to help testing with. it should be a v1.

**Comment by KrzysiekLegnica** [comment] 2020-04-07 18:58
I also have a washer and dryer for APIv2 and help with testing.

**Comment by ollo69** [comment] 2020-04-07 19:14
> Any plans on sending PRs back to the original wideq (https://github.com/sampsyo/wideq) or ha component (https://github.com/sampsyo/hass-smartthinq)? That may help to expand the number of testers. Personally I have a washer and dryer on APIv2, and will help testing anyway I can.

Send PR to this 2 project from here is not possible for differerent reason:
- this is not a fork, but is a new repository created from scratch. I created it after some experiment starting from many mods of the wideq original project
- the wideq part is quite different in the structure, this to better manage coexistence of the 2 API model abtracting the device concept and not the client
- the HA part is written for the most part from scratch for managing config flow and HA registry.

Create a PR from here will do the owner of original repository crazy.

**Comment by KrzysiekLegnica** [comment] 2020-04-07 20:13
Please enter your email, I'll send you logs.

**Comment by ollo69** [comment] 2020-04-07 20:18
> Please enter your email, I'll send you logs.

aolivero@gmail.com

**Comment by ollo69** [comment] 2020-04-07 21:07
Message from log:

![image](https://user-images.githubusercontent.com/60491700/78719559-66e09800-7924-11ea-8d24-54b456966c91.png)
 
This device do not use APIv1

**Comment by tayanov** [comment] 2020-04-08 08:04
i see something new in log.
I see example "remainTimeMinute': 49.0"
May be it later in log... but ...
i send email for you

**Comment by ollo69** [comment] 2020-04-08 08:05
Yes, I discovered some interesting information in your log, trying to understand. Stay tuned...

**Comment by tayanov** [comment] 2020-04-08 08:29
i dont now need launch full washing or toggle on off only?

**Comment by tayanov** [comment] 2020-04-08 13:27
i compare api answer frige and washer
frige                                        washer
'platformType': 'thinq1'          'platformType': 'thinq2'
guideType': 'TYPE1'                'guideType': 'TYPE2'
'deviceType': 101                   'deviceType': '201'


obviously see what devices have diffrent smart platform
as if have diffrent endpoint to api

**Comment by ollo69** [comment] 2020-04-08 18:03
Just released a new version, may be I found a solution, please test and provide feedback.
If should work, please not start complaining that not all sessor attributes are managed.( for sure I'm not managing course name).
Wait your feedback,

**Comment by daveonkels** [comment] 2020-04-08 18:10
Haven't run a load yet but it sees that the washer is on - so that's a great start.

<img width="351" alt="Screen Shot 2020-04-08 at 11 09 10 AM" src="https://user-images.githubusercontent.com/533642/78818492-9bd30600-7989-11ea-9fb6-94512c603b5f.png">

**Comment by tayanov** [comment] 2020-04-08 18:11
> Только что выпустили новую версию, может быть, я нашел решение, пожалуйста, протестируйте и предоставьте отзыв.
> Если должно сработать, пожалуйста, не начинайте жаловаться, что не все атрибуты сестер управляются (наверняка я не управляю названием курса).
> Ждите вашего отзыва,

You a superman!!! Its great. I see on off state. And many sensor. And no error in log

**Comment by ollo69** [comment] 2020-04-08 18:20
APIv2 should also be better from a performance point of view because do not require to poll every device.
Anyway is better wait for additional feedback.
When I'll have some more time I'll try to manage other states.

**Comment by towerhand** [comment] 2020-04-08 18:42
Recreated the integration again with the new version. Everything still works as before.

**Comment by daveonkels** [comment] 2020-04-09 00:15
Looks like you solved a few more states in v0.9.

<img width="359" alt="Screen Shot 2020-04-08 at 5 14 00 PM" src="https://user-images.githubusercontent.com/533642/78845126-8deaa880-79bc-11ea-8bc1-2268928c2c36.png">

**Comment by kenmaples** [comment] 2020-04-09 01:50
Looking better on my side also
![Screenshot_20200408-183038](https://user-images.githubusercontent.com/2633530/78849570-b3ca7a00-79c9-11ea-801a-01a37a0119b2.png)

**Comment by ollo69** [comment] 2020-04-09 09:29
To fix missing state I need a piece of log in debug mode during washer run.

**Comment by ollo69** [comment] 2020-04-13 16:59
I just released Dryer support, test can start now. Please provide feed-back and send to me logs (possible debug), because not having Dryer I wasn't able to do any test.

**Comment by tayanov** [comment] 2020-04-13 17:18
Good news. I not have dryer. But have frige. Ready to test in future

**Comment by rwarner** [comment] 2020-04-16 17:57
So excited over here. Just thought I'd add in my 2 cents.

Just setup this integration in HACS and was able to go through the whole workflow with a standard LG account. Detected my Washer while it was running and showed all the correct states. Alerted all the run_completed attributes as expected and ran my automations.

Seems to be working great for the US LGE Washer I have.

**Comment by KTibow** [comment] 2020-07-01 16:15
Just saying: 76 days old, time to close @ollo69?

**Closed** 2020-07-01 18:31 UTC

**Comment by tismofied** [comment] 2021-09-22 15:26
Just installed this integration in HACS, the documment says to "Simply add a new "integration" and look for "SmartThinQ LGE Sensors" among the proposed ones and follow setup worflow" I look in HA integrations and it's not showing up. how do I configure this component? please help

**Comment by ollo69** [comment] 2021-09-22 17:59
This is a closed issue, open a new one. Anyway try before cleaning your bowser cache.
